# Generated by Django 2.0 on 2017-12-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171214_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
        migrations.AlterField(
            model_name='post',
            name='edit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
